# Clinical Decision Support Service Configuration
spring:
  application:
    name: clinical-decision-support-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cds_db}
    username: ${DATABASE_USERNAME:cds_user}
    password: ${DATABASE_PASSWORD:cds_password}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # AI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        model: gpt-4-turbo
        temperature: 0.2
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: cds-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Server Configuration
server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /cds

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# CDS Specific Configuration
cds:
  rules:
    evaluation-timeout-ms: 5000
    max-concurrent-evaluations: 100
    cache-duration-minutes: 30
  
  ai:
    enabled: true
    confidence-threshold: 0.8
    max-recommendations: 5
  
  alerts:
    max-per-patient-per-day: 10
    suppress-duration-hours: 24
    require-acknowledgment: true

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:cds_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false

cds:
  ai:
    enabled: true
  alerts:
    require-acknowledgment: true